### ISSUE TITLE
Problem encoding/decoding `IndexedAttestation`

### ISSUE THREAD

**Issue by jtraglia** [flashbots/go-boost-utils#18]
## 📝 The Problem

When reviewing builder types, I noticed that the JSON encoding for `AttestingIndices` is missing the `string` option. The beacon API states (see reference for example) that this should be a list of `uint64` strings.

https://github.com/flashbots/go-boost-utils/blob/417a64679a5d4a2c12b64ff7ee918243d4ab34eb/types/builder.go#L62

I was expecting to see something like `json:"attesting_indices,string"` but, because it's an array, that won't work.

To verify my theory, I made the following test that will try to decode an `IndexedAttestation` JSON blob:

```go
func TestIndexedAttestation(t *testing.T) {
    input := `{
        "attesting_indices": [
            "1", "2", "3"
        ],
        "signature": "0x1c66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505cc411d61252fb6cb3fa0017b679f8bb2305b26a285fa2737f175668d0dff91cc1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af171505",
        "data": {
            "slot": "1",
            "index": "1",
            "beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
            "source": {
                "epoch": "1",
                "root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2"
            },
            "target": {
                "epoch": "1",
                "root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2"
            }
        }
    }`
    var result IndexedAttestation
    err := json.Unmarshal([]byte(input), &result)
    require.NoError(t, err)
}
```

It will pass if you change `attesting_indices` from `["1","2","3"]` to `[1,2,3]`. I think we need to add a `U64Str` type to `common.go` with `MarshalText`, `UnmarshalJSON`, and `UnmarshalText` methods.

## 📚 References

* https://ethereum.github.io/beacon-APIs/#/Beacon/getPoolAttesterSlashings
* https://stackoverflow.com/questions/49415573/golang-json-how-do-i-unmarshal-array-of-strings-into-int64

**Comment by metachris** [comment]
Good find! 👍 ping @lightclient

The solution here seems to be a uint64 type that marshalls to a string? 🤔 

Sadly the code duplication is for the reason that mergemock wanted to internalize all the types and not use any other repository for them. Maybe the stance has changed in the meantime @lightclient? We wanted to have a repository with only the types, rather than needing to import mergemock in other projects.

**Comment by metachris** [comment]
For reference, this is what i've been trying, which yet doesn't work: https://github.com/flashbots/go-boost-utils/compare/main...u64str-test1

**Comment by metachris** [comment]
See https://github.com/ferranbt/fastssz/issues/92 for the issue about the root cause at fastssz
