### ISSUE TITLE
Hardcoded constant values for ssz

### ISSUE THREAD

**Issue by terencechain** [flashbots/go-boost-utils#39]
I've seen a few hardcoded constants for ssz usages like `33` instead of `DEPOSIT_CONTRACT_DEPTH + 1`. It's a little concerning in the event of off-by-one errors or config mismatches. I'd recommend not hardcode ssz sizes as unnamed constants

**Comment by terencechain** [comment]
credit to @potuz for pointing this out

**Comment by metachris** [comment]
nice catch! will update

**Comment by metachris** [comment]
please reopen if you see any more opportunities for constants

**Comment by potuz** [comment]
I think this issue should not be closed. Many ssz sizes are hardcoded as unnamed constants and used in different parts of code. Either they should be a named constant or the types should have a function returning their serialized size

**Comment by metachris** [comment]
@potuz could you link to some examples please?

**Comment by metachris** [comment]
Doesn't Prysm do it the same way too? eg: https://github.com/prysmaticlabs/prysm/blob/develop/proto/prysm/v1alpha1/beacon_block.pb.go#L305 - how would you encode these with consts?

**Comment by potuz** [comment]
> @potuz could you link to some examples please? (reopened the issue)

Indeed I could have sworn that I saw a bunch of hardcoded ssz sizes in the deposit fix PR, my mistake, it must've been the encoded files. I can now only see hardcoded sizes when unmarshaling, like this one

https://github.com/flashbots/go-boost-utils/blob/main/types/common.go#L218

**Comment by metachris** [comment]
No todo's anymore. The remaining constants are the auto-generated ones. Closing this for now, feel free to comment to reopen.
